name: Run Unit Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 


jobs:
  test:
    environment: secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          POSTGRESQL_DB_USER: ${{ secrets.POSTGRESQL_DB_USER }}
          POSTGRESQL_DB_PASSWORD: ${{ secrets.POSTGRESQL_DB_PASSWORD }}
          POSTGRESQL_DB: ${{ secrets.POSTGRESQL_DB }}
          POSTGRESQL_DB_PORT: ${{ secrets.POSTGRESQL_DB_PORT }}
          POSTGRESQL_DB_HOST: ${{ secrets.POSTGRESQL_DB_HOST }}

        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Run tests
        run: python Test.py